# Generated by Django 5.1.3 on 2024-12-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
